"""Add APIKey model

Revision ID: 19518c1a4831
Revises: 4b228fb48e45
Create Date: 2025-08-13 16:50:06.129711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19518c1a4831'
down_revision = '4b228fb48e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key')
    # ### end Alembic commands ###
